#!/bin/bash
# get all disks into an array
disks=($(ls  /dev/sdc* /dev/sdd* | grep -v '[0-9]'))
echo $disks; 
 #loop over disks in array
for i in $(echo ${disks[@]}); do
    # check if it has a partition
    diskcheck=$(ls ${i}* | grep '[0-9]')
     #if not, print it
    if [ -z "$diskcheck" ]; then
        echo $i[1];
    fi
done
length=${#disks[@]}
echo $length;
for ((i=0;i<$length; i++))

do
  disk_name="${disks[i]}"
  echo $disk_name
 dir_name="dir$i"
 mount_points=("/mnt/${dir_name}")
 echo $mount_points
 mount_point="${mount_points[i]}"
#we should format the disk to ext4
sudo mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard "$disk_name"
#create the mount point 
sudo mkdir -p "$mount_point"
# Mount the disk
 sudo mount -o discard,defaults "$disk_name" "$mount_point"
#give permission to the directory
 sudo chmod a+w "$mount_point"
 # Add the disk to /etc/fstab for automatic mounting on boot
  echo UUID=$(sudo blkid -s UUID -o value "$disk_name") "$mount_point" ext4 discard,defaults,nofail 0 2 | sudo tee -a /etc/fstab
done
